### ISSUE TITLE
When updating a dataset that is attached to an `Upload` the reindex process isn't being applied to the `Upload`

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/search-api#148]
If you change the status of any dataset contained in this Upload (https://data.dev.sennetconsortium.org/upload?uuid=efec9253c819cf74bbaaeefaa7ed746f/) using the revert button, the status changes in the UI for that dataset but not in the table of `Datsets` on the Upload Page: 
<img width="1481" alt="image" src="https://github.com/sennetconsortium/search-api/assets/7218802/8f7b7393-0669-46ba-bcc0-a8e2328bb7fb">

The Search API should be updated to check if a dataset is `in_upload` and then reindex the upload as well.

**Comment by libpitt** [comment]
@maxsibilla 
You can look into this some more but seems like there is an issue of latency. The following screenshot 
![entity](https://github.com/sennetconsortium/search-api/assets/115558393/a89d0d88-bf69-4c01-8743-516ca18d0265)
I had issued a revert to another status but it still showed the old status, in this case `Invalid`.
When search-api issues a `entities/<id> GET`, the old status is still in the dict. Like the update is not complete within entity-api before the call to reindex in search-api. If we leave the breakpoint to linger a few seconds in `entities/<id> PUT` call before it gets to reindex in search-api, say at line 1404 `reindex_entity(entity_dict['uuid'], user_token)`, by time line 226 in search-api, the entity would've been updated as expected. Seems a case of latency.
