### ISSUE TITLE
Remove old /assaytype UBKG endpoint usages

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/search-api#218]
The entire file `sennet_endpoints.py` (https://github.com/sennetconsortium/search-api/blob/main/src/libs/sennet_endpoints.py) can be removed as all it does it return the UBKG /assaytype response.

`assay_type.py`(https://github.com/sennetconsortium/search-api/blob/main/src/libs/assay_type.py) and `assay_type_schema.yaml` (https://github.com/sennetconsortium/search-api/blob/main/src/libs/assay_type_schema.yml) can also be removed.

**Comment by libpitt** [comment]
https://github.com/sennetconsortium/ingest-api/issues/511

**Comment by libpitt** [comment]
https://github.com/orgs/sennetconsortium/projects/9/views/1?pane=issue&itemId=72372238
