### ISSUE TITLE
Add support for `Uploads` Search API

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/search-api#82]
- [x] Port over `translate_upload` function https://github.com/hubmapconsortium/search-api/blob/f5f91d6905584cd67e98f2311fe0b36990e5eafa/src/hubmap_translator.py#L446
- [x] Update `add_calculated_fields` to utilize variable `entity_types_with_display_subtype`
https://github.com/hubmapconsortium/search-api/blob/f5f91d6905584cd67e98f2311fe0b36990e5eafa/src/hubmap_translator.py#L45C1-L45C34
https://github.com/hubmapconsortium/search-api/blob/f5f91d6905584cd67e98f2311fe0b36990e5eafa/src/hubmap_translator.py#L763

**Comment by tjmadonna** [comment]
`Upload` implemented in `sennet_translator.py`

Todos in `sennet_translator.py`. Waiting on UBKG issue [#77](https://github.com/x-atlas-consortia/ubkg-api/issues/77).
- https://github.com/sennetconsortium/search-api/blob/4c1e6c50376e059e951db367dd55aea0d338cade/src/sennet_translator.py#L78
- https://github.com/sennetconsortium/search-api/blob/4c1e6c50376e059e951db367dd55aea0d338cade/src/sennet_translator.py#L721
